set lines=999 columns=999
set fuoptions=maxhorz,maxvert
set transp=10
set guioptions-=R
set guioptions-=r
set guioptions-=L
set guioptions-=l
set guioptions-=e
" set gfn=Inconsolata:h12

set cursorline!

" MatchParen is rather pointless and very slow
NoMatchParen

" Don't show tooltip help for hovered word
set noballooneval

macmenu Edit.Font.Bigger key=<nop>
macmenu Edit.Font.Smaller key=<nop>

