# Prevent tmux from screwing up my PATH
if [ -f /etc/profile ]; then
  PATH=""
  source /etc/profile
fi

HISTSIZE=10000
HISTFILESIZE=10000

eval "$(rbenv init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

PATH=./bin:~/bin:$PATH

alias l="ls -l"
alias ll="ls -la"
alias ..="cd .."

alias be="bundle exec "
alias rg="bundle exec rails generate "
alias rd="bundle exec rails destroy "
alias alert="say done"
alias so="source ~/.bash_profile"
alias pss="ps ax | grep -v grep | grep "

export EDITOR="/usr/local/bin/nvim"
export GPG_TTY=`tty`
export RAILS_SYSTEM_TESTING_SCREENSHOT=inline

# Keyboardio
export SKETCHBOOK_DIR=$HOME/Documents/Arduino

# Easily start and kill tmuxinator
alias tstart="tmuxinator start "
alias tkill="stop-services; tmux kill-session"

source /Users/cvincent/.pgvm/pgvm_env

source /Users/cvincent/.bash_secret

export PATH="$HOME/.cargo/bin:$PATH"
